In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_log_error
from sklearn.metrics.scorer import make_scorer
from sklearn.model_selection import cross_val_score

C:\Users\animathur\AppData\Local\Continuum\anaconda3\envs\py3-TensorFlow2\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)


In [2]:
data_npz = np.load('./preprocessed_data_with_industry.npz')
X = data_npz['inputs'].astype(np.float)
y = data_npz['targets'].astype(np.float)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [57]:
reg.intercept_

8.114877092934329

In [58]:
reg.coef_

array([ 5.42520217e-01,  3.97021251e-01,  4.47615977e-02, -1.01726432e-01,
       -2.05059221e-01, -9.32254048e-02, -1.47935022e-01, -3.54969196e-02,
        3.25677261e-01, -1.76503869e-02,  2.53101667e-01, -3.66713721e-02,
       -1.90073952e-02,  1.67269997e-01, -1.39950304e-03, -3.87055521e-02,
       -2.56948445e-02, -1.28173018e-02,  1.12513997e-01,  2.84343115e-02,
       -1.75291315e-02, -9.06939039e-02,  9.07298728e-02,  5.75266079e-03,
       -1.16495582e-01,  1.76824971e-01, -2.77131775e-02, -1.55581540e-01,
       -1.34446408e-01,  1.58893102e-01, -1.08019342e-01,  1.30620665e-01,
        1.22164812e-02, -3.44466159e-02,  3.01563088e-01, -1.26281938e-02,
        1.02159056e-02,  2.52340443e-01,  7.40928500e-02, -1.25780343e-01,
        2.81190428e-01, -2.98171547e-03, -1.46283787e-02, -3.07803419e-02,
       -6.93388833e-03, -2.11071114e-02, -1.71341489e-01,  1.77648161e-01,
        1.11074990e-01, -1.46970885e-02, -5.44369303e-02,  1.24487759e-01,
        6.68288075e-02,  

In [6]:
def custom_rmsle_scorer(y_true,y_predicted):
    y_predicted[y_predicted < 0] = 0
    return np.sqrt(mean_squared_log_error(y_true, y_predicted))

In [10]:
cv_reg = LinearRegression()
cv_scores = cross_val_score(cv_reg, X, y, scoring=make_scorer(custom_rmsle_scorer, greater_is_better=False))

In [11]:
cv_scores

array([-0.4700274 , -0.46584599, -0.46796791, -0.46867393, -0.46471525])

In [13]:
1 + cv_scores

array([0.5299726 , 0.53415401, 0.53203209, 0.53132607, 0.53528475])