In [1]:
import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_log_error
from sklearn.metrics.scorer import make_scorer
from sklearn.model_selection import cross_val_score

C:\Users\animathur\AppData\Local\Continuum\anaconda3\envs\py3-TensorFlow2\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)


In [2]:
data_npz = np.load('./preprocessed_data_with_industry.npz')
X = data_npz['inputs'].astype(np.float)
y = data_npz['targets'].astype(np.float)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
reg = SGDRegressor()
reg.fit(X_train, y_train)

C:\Users\animathur\AppData\Local\Continuum\anaconda3\envs\py3-TensorFlow2\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1211: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDRegressor()

In [6]:
reg.intercept_

array([38788028.23298803])

In [7]:
reg.coef_

array([-1.43434228e+07, -1.33862067e+07,  7.90499424e+06, -3.76365490e+06,
       -1.01559042e+07,  2.46634536e+06, -6.25504035e+06, -2.40670544e+07,
       -1.29461128e+07,  2.07008672e+07, -7.09222084e+06, -5.78889051e+06,
        3.63671670e+06, -7.27133963e+06, -1.28680197e+06, -1.57765917e+07,
       -2.16254708e+06, -1.60536560e+07, -1.65428858e+07, -1.45456776e+07,
        1.06980704e+06, -1.90946878e+07, -7.75906646e+06, -1.70419475e+06,
       -7.87147460e+06, -3.82016188e+05, -2.40865782e+07, -3.62407903e+07,
       -5.01971901e+07,  3.55890721e+08,  1.34094286e+08,  1.18243509e+07,
        6.71986246e+07,  1.12013276e+06, -1.70166349e+07,  3.10434270e+07,
        1.62778458e+07,  2.12266670e+07,  1.60137980e+07,  3.90613954e+06,
       -7.51272398e+07, -1.01311863e+05, -7.26709449e+06,  8.77775953e+06,
       -2.28343364e+06, -1.36425947e+06,  9.67316234e+06,  3.41720900e+06,
       -2.66737635e+06, -8.88625100e+06, -7.55865851e+06, -3.16859049e+05,
        3.00416380e+06, -

In [8]:
reg.score(X_test, y_test)

-2.0890213211829416e+19

In [9]:
def custom_rmsle_scorer(y_true,y_predicted):
    y_predicted[y_predicted < 0] = 0
    return np.sqrt(mean_squared_log_error(y_true, y_predicted))

In [10]:
cv_reg = SGDRegressor()
cv_scores = cross_val_score(cv_reg, X, y, scoring=make_scorer(custom_rmsle_scorer, greater_is_better=False))

C:\Users\animathur\AppData\Local\Continuum\anaconda3\envs\py3-TensorFlow2\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1211: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


In [11]:
cv_scores

array([-13.49162479, -11.8756952 , -13.48765671, -14.70785032,
       -13.59484078])

In [12]:
1 + cv_scores

array([-12.49162479, -10.8756952 , -12.48765671, -13.70785032,
       -12.59484078])